version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  neo4j:
    image: neo4j:3.5.17
    container_name: neo4j-server
    network_mode: 'bridge'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
      - '2004:2004'
    restart: unless-stopped
    volumes:
      - $HOME/datadrive/neo4j/plugins:/plugins
      - $HOME/datadrive/neo4j/data:/data
      - $HOME/datadrive/neo4j/import:/import
      - $HOME/datadrive/neo4j/logs:/logs
      - $HOME/datadrive/neo4j/conf:/conf
    environment:
      #- NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/neo123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      #- NEO4J_apoc_import_file_enabled=true
      #- NEO4J_apoc_export_file_enabled=true
      #- NEO4J_dbms_backup_enabled=true
      - NEO4J_dbms_transaction_timeout=60s
      #- NEO4j_apoc_trigger_enabled=true
    logging:
      options:
        tag: 'ImageName:{{.ImageName}}/Name:{{.Name}}/ID:{{.ID}}/ImageFullID:{{.ImageFullID}}'
